{
 "title": "Giropops-Senhas",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Memória Utilizada - Por Node",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (instance:node_memory_utilisation:ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods por Namespace",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (node_namespace_pod:kube_pod_info:)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Senhas Geradas incluindo CARACTERES ESPECIAIS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (senha_gerada_caracteres_especiais_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Senhas Geradas incluindo NÚMEROS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (senha_gerada_numeros_total{service=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Erros de Conexão com o Redis",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (redis_connection_errors_total{service=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Senhas geradas SEM CARACTERES ESPECIAIS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (senha_gerada_sem_caracteres_especiais_total{service=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Senhas Geradas SEM NÚMEROS",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pod) (senha_gerada_sem_numeros_total{container=\"giropops-senhas\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Senhas Geradas no TOTAL",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(container) (senha_gerada_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória por POD",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(container) (container_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo para gerar uma senha",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by(pod) (tempo_gerar_senha_sum)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}