{{- range $deployment := .Values.deployments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deployment.name }}
  namespace: {{ $deployment.namespace }}
  labels:
    env: {{ if $.Values.env }}{{ $.Values.env }}{{ else }}dev{{ end }}
    {{- range $key, $value := $deployment.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  replicas: {{ $deployment.replicas }}
  selector:
    matchLabels:
      app: {{ $deployment.labels.app }}
  template:
    metadata:
      labels:
        env: {{ if $.Values.env }}{{ $.Values.env }}{{ else }}dev{{ end }}
        {{- range $key, $value := $deployment.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec:
      serviceAccountName: {{ $deployment.serviceAccountName }}
      {{- if $deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- range $secret := $deployment.imagePullSecrets }}
        - name: {{ $secret.name }}
        {{- end }}
      {{- end }}
      containers:
        {{- range $container := $deployment.containers }}
        - name: {{ $container.name }}
          image: {{ $container.image }}
          ports:
            {{- range $port := $container.ports }}
            - containerPort: {{ $port.containerPort }}
            {{- end }}
          env:
            {{- range $env := $container.env }}
            - name: {{ $env.name }}
              value: {{ $env.value }}
            {{- end }}
          resources:
            limits:
              memory: {{ $container.resources.limits.memory }}
              cpu: {{ $container.resources.limits.cpu }}
            requests:
              memory: {{ $container.resources.requests.memory }}
              cpu: {{ $container.resources.requests.cpu }}
          securityContext:
            allowPrivilegeEscalation: {{ $container.securityContext.allowPrivilegeEscalation }}
            runAsUser: {{ $container.securityContext.runAsUser }}
            runAsGroup: {{ $container.securityContext.runAsGroup }}
            capabilities:
              drop:
                {{- range $capability := $container.securityContext.capabilities.drop }}
                - {{ $capability }}
                {{- end }}
              {{- if $container.securityContext.capabilities.add }}
              add:
                {{- range $capability := $container.securityContext.capabilities.add }}
                - {{ $capability }}
                {{- end }}
              {{- end }}
          livenessProbe:
            {{- toYaml $container.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $container.readinessProbe | nindent 12 }}
          {{- if $container.command }}
          command:
            {{- range $cmd := $container.command }}
            - {{ $cmd }}
            {{- end }}
          {{- end }}
        {{- end }}
---
{{- end }}