apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-pod-probes
  annotations:
    pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet
    policies.kyverno.io/title: Require Pod Probes
    policies.kyverno.io/category: Best Practices, EKS Best Practices
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  background: true
  rules:
  - name: validate-probes
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - harbor
          - ingress-nginx
          - kube-system
          - kyverno
          - monitoring
          - locust
          - keda
    preconditions:
      all:
      - key: "{{request.operation || 'BACKGROUND'}}"
        operator: AnyIn
        value:
        - CREATE
        - UPDATE
    validate:
      message: "Você deve incluir as Probies para fazer deploy!"
      foreach:
      - list: request.object.spec.containers[]
        deny:
          conditions:
            all:
            - key: livenessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
            - key: startupProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"
            - key: readinessProbe
              operator: AllNotIn
              value: "{{ element.keys(@)[] }}"