apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      exclude:
        resources:
          namespaces:
          - harbor
          - ingress-nginx
          - kube-system
          - kyverno
          - monitoring
          - locust

      verifyImages:
      - imageReferences:
        - "harbor.fabiobartoli.com.br/*"
        attestors:
        - count: 1
          entries:
          - keys:
              secretRef:
                name: cosign-public-key