apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-sensitive-env-vars
spec:
  validationFailureAction: Enforce
  failurePolicy: Fail
  rules:
    - name: disallow-sensitive-env-vars
      match:
        any:
        - resources:
            kinds:
              - Pod
      validate:
        message: "Não é permitido passar senhas como variáveis nesse Cluster! Use Secrets ao invés disso"
        pattern:
          spec:
            containers:
              - env:
                  - name: "!*KEY*"
                  - name: "!*SECRET*"
                  - name: "!*TOKEN*"
